version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/database
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: "1G"
          cpus: "1.0"
        reservations:
          memory: "512M"
          cpus: "0.5"
    mem_limit: "1g"
    cpus: "1.0"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "0.5"
        reservations:
          memory: "256M"
          cpus: "0.25"
    mem_limit: "512m"
    cpus: "0.5"

volumes:
  postgres-data:
